import { describe, it, expect } from "vitest";
import { extractJsonObject } from "./json-extract";

describe("extractJsonObject", () => {
  describe("happy path", () => {
    it("parses a plain JSON object string", () => {
      const input = '{"key":"value","num":42}';
      expect(extractJsonObject(input)).toEqual({ key: "value", num: 42 });
    });

    it("parses a plain JSON array string", () => {
      const input = '[1,2,3]';
      expect(extractJsonObject(input)).toEqual([1, 2, 3]);
    });

    it("strips <think>...</think> tags before parsing", () => {
      const input = "<think>some thought process</think>{" +
        '"key":"value"' +
        "}";
      expect(extractJsonObject(input)).toEqual({ key: "value" });
    });

    it("strips ```json code fence from start", () => {
      const input = "```json\n{\"key\":\"value\"}\n```";
      expect(extractJsonObject(input)).toEqual({ key: "value" });
    });

    it("strips ``` code fence from start and end", () => {
      const input = "```\n{\"key\":\"value\"}\n```";
      expect(extractJsonObject(input)).toEqual({ key: "value" });
    });

    it("strips ```json fence and <think> tags together", () => {
      const input =
        "<think>inner thoughts</think>\n```json\n{\"a\":1}\n```\n<think>more thoughts</think>";
      expect(extractJsonObject(input)).toEqual({ a: 1 });
    });

    it("returns a nested object correctly", () => {
      const input = '{"outer":{"inner":true},"arr":[null,{}]}';
      expect(extractJsonObject(input)).toEqual({
        outer: { inner: true },
        arr: [null, {}],
      });
    });
  });

  describe("fallback extraction (malformed JSON but has braces)", () => {
    it("extracts object when JSON.parse fails due to surrounding text", () => {
      // Direct parse fails because "result: " prefix isn't valid JSON
      // Fallback extracts {"x":1} which is valid JSON
      const input = 'result: {"x":1}';
      expect(extractJsonObject(input)).toEqual({ x: 1 });
    });

    it("extracts from input with leading non-JSON text", () => {
      const input = "Here is the result: {\"x\":1}";
      expect(extractJsonObject(input)).toEqual({ x: 1 });
    });

    it("extracts from input with trailing non-JSON text", () => {
      const input = "{\"x\":1}\n\nGenerated by AI";
      expect(extractJsonObject(input)).toEqual({ x: 1 });
    });
  });

  describe("edge cases", () => {
    it("throws when no braces are found at all", () => {
      expect(() => extractJsonObject("no braces here")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when only opening brace is present", () => {
      expect(() => extractJsonObject("only { exists")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when only closing brace is present", () => {
      expect(() => extractJsonObject("only } exists")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when opening brace comes after closing brace", () => {
      expect(() => extractJsonObject("} {")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when string is empty", () => {
      expect(() => extractJsonObject("")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when string is only whitespace", () => {
      expect(() => extractJsonObject("   \n\t  ")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("throws when only think tags are present with no object", () => {
      expect(() => extractJsonObject("<think> nothing useful</think>")).toThrow(
        "No JSON object found in model response."
      );
    });

    it("handles string with only fences and whitespace", () => {
      expect(() => extractJsonObject("```json\n\n```")).toThrow(
        "No JSON object found in model response."
      );
    });
  });
});
