import type { Roadbook } from "@/lib/roadbook-types";

export const sampleRoadbook: Roadbook = {
  title: "大理 4 天松弛路书",
  subtitle: "从古城到洱海，把风、咖啡、日落和白族生活感串成一条不赶路的路线。",
  destination: "云南大理",
  durationLabel: "4 天 3 晚",
  travelerLabel: "2 位轻松出片型旅行者",
  budgetLabel: "中等预算",
  concept: "每天只抓 3-4 个重点体验，让路书既好看，也真的能拿来出发。",
  bestFor: ["第一次去大理", "喜欢慢节奏", "想拍照但不想赶景点", "希望路线顺一点"],
  highlights: ["古城 Citywalk", "洱海骑行", "白族文化体验", "日落咖啡", "轻量预算拆分"],
  summary: {
    routeTheme: "古城生活感 + 洱海风景线",
    transportPlan: "核心区域步行/打车，环海段电动车或包车",
    stayArea: "大理古城或才村附近",
    rhythm: "上午慢启动，下午重点体验，傍晚留给日落",
  },
  days: [
    {
      day: 1,
      title: "抵达大理，把节奏放慢",
      area: "大理古城",
      mood: "落地、适应、轻松散步",
      routeSummary: "入住后围绕古城慢走，先把方向感建立起来。",
      commuteNote: "从机场/车站到古城建议打车或预约接送。",
      budgetNote: "第一天以住宿和轻餐为主，保留体力。",
      stops: [
        {
          id: "sample-d1-1",
          name: "大理古城南门",
          time: "15:00",
          category: "culture",
          addressHint: "云南大理大理古城南门",
          why: "适合作为第一站，进入古城主街区，开始建立路线感。",
          duration: "40 分钟",
          tip: "先不要买太多伴手礼，后面还有更适合逛的时间。",
        },
        {
          id: "sample-d1-2",
          name: "人民路",
          time: "16:00",
          category: "shopping",
          addressHint: "云南大理大理古城人民路",
          why: "咖啡、小店、街头音乐都集中，适合慢慢进入大理状态。",
          duration: "1.5 小时",
          tip: "适合拍街景，但注意避开人最多的路口。",
        },
        {
          id: "sample-d1-3",
          name: "五华楼",
          time: "18:00",
          category: "view",
          addressHint: "云南大理五华楼",
          why: "古城标志点，傍晚光线更柔和。",
          duration: "30 分钟",
          tip: "如果当天疲惫，可以只做外观打卡。",
        },
      ],
      food: ["白族家常菜", "古城咖啡", "鲜花饼试吃"],
      photoTips: ["古城石板路", "傍晚楼阁剪影", "人民路店招"],
    },
    {
      day: 2,
      title: "洱海边的一整天",
      area: "才村 / 磻溪 / 廊桥",
      mood: "风景、骑行、日落",
      routeSummary: "沿洱海西线慢慢移动，把拍照点和咖啡时间留足。",
      commuteNote: "建议电动车或包车，注意防晒和风。",
      budgetNote: "交通和咖啡体验是当天主要花费。",
      stops: [
        {
          id: "sample-d2-1",
          name: "才村码头",
          time: "10:00",
          category: "view",
          addressHint: "云南大理才村码头",
          why: "离古城近，适合开始洱海边的慢行路线。",
          duration: "1 小时",
          tip: "上午人相对少，适合拍水面和远山。",
        },
        {
          id: "sample-d2-2",
          name: "磻溪 S 湾",
          time: "14:30",
          category: "view",
          addressHint: "云南大理磻溪村S湾",
          why: "经典环海拍照点，画面辨识度高。",
          duration: "1.5 小时",
          tip: "不要只挤在最热门位置，往两侧走更容易出片。",
        },
        {
          id: "sample-d2-3",
          name: "廊桥",
          time: "17:30",
          category: "view",
          addressHint: "云南大理洱海廊桥",
          why: "适合等一场不赶路的日落。",
          duration: "1 小时",
          tip: "日落受天气影响，提前查当天云量。",
        },
      ],
      food: ["洱海边咖啡", "烤乳扇", "菌菇火锅"],
      photoTips: ["S 湾弯道", "洱海逆光", "骑行背影"],
    },
    {
      day: 3,
      title: "白族村落和生活感",
      area: "喜洲 / 周城",
      mood: "文化、建筑、手作",
      routeSummary: "从喜洲古镇到周城，换一种更生活化的大理视角。",
      commuteNote: "建议包车或顺风车，减少换乘成本。",
      budgetNote: "可安排一项扎染或手作体验。",
      stops: [
        {
          id: "sample-d3-1",
          name: "喜洲古镇",
          time: "10:00",
          category: "culture",
          addressHint: "云南大理喜洲古镇",
          why: "白族建筑和小镇生活感集中，适合慢逛。",
          duration: "2 小时",
          tip: "拍建筑时注意不要打扰居民。",
        },
        {
          id: "sample-d3-2",
          name: "严家大院",
          time: "13:30",
          category: "culture",
          addressHint: "云南大理喜洲严家大院",
          why: "更系统地理解白族民居和院落结构。",
          duration: "1 小时",
          tip: "出发前核验开放时间。",
        },
        {
          id: "sample-d3-3",
          name: "周城村",
          time: "16:00",
          category: "culture",
          addressHint: "云南大理周城村",
          why: "适合安排扎染体验，也能拍到更安静的村落画面。",
          duration: "2 小时",
          tip: "手作体验建议提前预约。",
        },
      ],
      food: ["喜洲粑粑", "白族三道茶", "本地小炒"],
      photoTips: ["白墙青瓦", "院落门头", "扎染布料细节"],
    },
    {
      day: 4,
      title: "留白、复盘、带走大理",
      area: "古城 / 返程",
      mood: "轻松收尾",
      routeSummary: "最后一天不要塞太满，适合补拍、买伴手礼、整理照片。",
      commuteNote: "根据返程时间预留 2-3 小时机动。",
      budgetNote: "控制伴手礼预算，避免临走冲动消费。",
      stops: [
        {
          id: "sample-d4-1",
          name: "床单厂艺术区",
          time: "10:00",
          category: "culture",
          addressHint: "云南大理床单厂艺术区",
          why: "适合补一点年轻、松弛、创意感画面。",
          duration: "1.5 小时",
          tip: "店铺开门时间不一，上午可慢一点出门。",
        },
        {
          id: "sample-d4-2",
          name: "大理古城",
          time: "12:00",
          category: "shopping",
          addressHint: "云南大理大理古城",
          why: "补买伴手礼和最后一顿轻餐。",
          duration: "2 小时",
          tip: "返程日不要安排太远的点。",
        },
      ],
      food: ["轻食咖啡", "鲜花饼", "本地米线"],
      photoTips: ["手账式收尾照片", "伴手礼平铺", "返程前合照"],
    },
  ],
  budget: [
    { label: "住宿", amount: "1200-2200 元", note: "古城/才村舒适型民宿，按 3 晚估算。" },
    { label: "餐饮", amount: "800-1400 元", note: "含咖啡、正餐和小吃体验。" },
    { label: "交通", amount: "500-1200 元", note: "含接送、打车、电动车或包车。" },
    { label: "体验", amount: "300-800 元", note: "扎染、门票或临时体验项目。" },
  ],
  packing: ["防晒霜", "墨镜", "轻薄外套", "舒服鞋", "充电宝", "可折叠袋"],
  reminders: ["核验开放时间和预约要求", "环海注意防晒和风", "返程日保留机动时间", "不要把 AI 生成内容当成已核验事实"],
  disclaimer: "AI 生成的旅行建议仅用于规划参考。出发前请核验营业时间、票价、预约、交通、天气与安全信息。",
};
